# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_product_services_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_created=True)),
                ('content', models.CharField(max_length=400)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
