# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='news',
        ),
    ]
